export default function sitemap() {
    return [
      {
        url: 'https://cyrilgouv.com',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/contact',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/legales/mentions-legales',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/a-propos',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/temoignages',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-biscarrosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-biscarrosse-plage-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-parentis-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sanguinet-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-ychoux-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-gastes-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-liposthey-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pissos-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sainte-eulalie-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pontenx-les-forges-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-paul-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-aureilhan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mimizan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mimizan-plage-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-escource-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lue-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-labouheyre-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-solferino-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-bias-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-commensacq-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saugnac-et-muret-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sabres-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mont-de-marsan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-dax-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-paul-les-dax-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-tarnos-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-pierre-du-mont-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-capbreton-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-soustons-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-vincent-de-tyrosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-labenne-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-aire-sur-l-adour-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-martin-de-seignanx-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-ondres-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-morcenx-la-nouvelle-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-sever-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-hagetmau-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-seignosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-cazaux-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
    ]
}