export default function sitemap() {
    return [
      {
        url: 'https://cyrilgouv.com',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/contact',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/legales/mentions-legales',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/a-propos',
        lastModified: new Date(),
        changeFrequency: 'yearly',
        priority: 1,
      },
      {
        url: 'https://cyrilgouv.com/temoignages',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations/le-feenomene-du-recrutement',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations/cabinet-sl-consulting',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations/les-gites-de-la-lumineuse',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations/cheval-d-or',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/realisations/yamitsu',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-biscarrosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-biscarrosse-plage-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-parentis-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sanguinet-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-ychoux-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-gastes-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-liposthey-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pissos-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sainte-eulalie-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pontenx-les-forges-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-paul-en-born-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-aureilhan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mimizan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mimizan-plage-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-escource-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lue-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-labouheyre-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-solferino-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-bias-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-commensacq-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saugnac-et-muret-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sabres-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mont-de-marsan-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-dax-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-paul-les-dax-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-tarnos-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-pierre-du-mont-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-capbreton-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-soustons-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-vincent-de-tyrosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-labenne-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-aire-sur-l-adour-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-martin-de-seignanx-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-ondres-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-morcenx-la-nouvelle-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-sever-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-hagetmau-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-seignosse-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-cazaux-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-mios-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-biganos-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-le-teich-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-gujan-mestras-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-la-teste-de-buch-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-arcachon-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pyla-sur-mer-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-salles-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-le-barp-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-marcheprime-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-audenge-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lanton-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-andernos-les-bains-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-ares-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lege-cap-ferret-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-le-porge-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lacanau-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-dompierre-sur-besbre-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-diou-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-beaulon-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-thiel-sur-acolin-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-vaumas-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-pourcain-sur-besbre-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-leon-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-chevagnes-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-montbeugny-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-lusigny-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-chapeau-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-neuilly-le-real-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-jaligny-sur-besbre-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-toulon-sur-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-yzeure-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-moulins-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-avermes-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-pierrefitte-sur-loire-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-coulanges-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-molinet-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-monetay-sur-loire-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-gilly-sur-loire-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-aubin-sur-loire-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-bourbon-lancy-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-saint-agnan-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-digoin-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-paray-le-monial-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-charolles-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-gueugnon-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-departement-des-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-departement-de-l-allier-03',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-departement-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-departement-saone-et-loire-71',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-region-nouvelle-aquitaine',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-region-auvergne-rhone-alpes',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-bourbonnais',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-nord-des-landes-40',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
      {
        url: 'https://cyrilgouv.com/services/creation-site-internet-sud-gironde-33',
        lastModified: new Date(),
        changeFrequency: 'monthly',
        priority: 0.8,
      },
    ]
}